/*
 * gpu_tray — Advanced Optimus dGPU tray switcher
 * Targets: Intel iGPU + NVIDIA dGPU laptops with Advanced Optimus (MUX switch)
 * Build:   See .github/workflows/build.yml  (MSVC + NVAPI NuGet, no local install)
 *
 * Behaviour:
 *   Launch  → request dGPU MUX via NVAPI, tray icon = green "N" + GPU name tooltip
 *   Exit    → revert MUX to iGPU/auto,    tray icon = blue  "I" briefly, then gone
 *   Right-click menu → current GPU label, manual revert, Exit
 */

#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <shellapi.h>
#include <string>
#include <strsafe.h>

// ── NVAPI dynamic loading ────────────────────────────────────────────────────
// We never link nvapi64.lib directly; we load the DLL at runtime so the app
// still launches (and falls back gracefully) on systems without NVIDIA drivers.
#include "nvapi_interface.h"   // minimal typedefs generated by CMake / copied in

typedef void* (*NvAPI_QueryInterface_t)(unsigned int);
typedef int   (*NvAPI_Initialize_t)();
typedef int   (*NvAPI_Unload_t)();
typedef int   (*NvAPI_GetDisplayDriverVersion_t)(void*, void*);

// MUX switch function IDs (Advanced Optimus, driver 510+)
// NvAPI_Disp_SetPreferredDGPU — requests that the MUX switch to dGPU output
#define NVAPI_ID_DISP_SET_PREFERRED_DGPU    0x5F4C2664u
// NvAPI_Disp_GetCurrentDGPUMode — queries active MUX state
#define NVAPI_ID_DISP_GET_CURRENT_DGPU_MODE 0x0DBAC0B0u

typedef int (*NvAPI_Disp_SetPreferredDGPU_t)(unsigned int gpuIndex, unsigned int enable);
typedef int (*NvAPI_Disp_GetCurrentDGPUMode_t)(unsigned int* pMode);

struct NvapiCtx {
    HMODULE                         dll            = nullptr;
    NvAPI_QueryInterface_t          QueryInterface = nullptr;
    NvAPI_Initialize_t              Initialize     = nullptr;
    NvAPI_Unload_t                  Unload         = nullptr;
    NvAPI_Disp_SetPreferredDGPU_t   SetDGPU        = nullptr;
    NvAPI_Disp_GetCurrentDGPUMode_t GetMode        = nullptr;
    bool                            ok             = false;
};

static NvapiCtx g_nvapi;

static bool NvapiLoad()
{
    g_nvapi.dll = LoadLibraryA("nvapi64.dll");
    if (!g_nvapi.dll) g_nvapi.dll = LoadLibraryA("nvapi.dll"); // 32-bit fallback
    if (!g_nvapi.dll) return false;

    g_nvapi.QueryInterface =
        (NvAPI_QueryInterface_t)GetProcAddress(g_nvapi.dll, "nvapi_QueryInterface");
    if (!g_nvapi.QueryInterface) return false;

    g_nvapi.Initialize     = (NvAPI_Initialize_t)          g_nvapi.QueryInterface(0x0150E828u);
    g_nvapi.Unload         = (NvAPI_Unload_t)              g_nvapi.QueryInterface(0xD22BDD7Eu);
    g_nvapi.SetDGPU        = (NvAPI_Disp_SetPreferredDGPU_t)   g_nvapi.QueryInterface(NVAPI_ID_DISP_SET_PREFERRED_DGPU);
    g_nvapi.GetMode        = (NvAPI_Disp_GetCurrentDGPUMode_t) g_nvapi.QueryInterface(NVAPI_ID_DISP_GET_CURRENT_DGPU_MODE);

    if (!g_nvapi.Initialize) return false;
    int status = g_nvapi.Initialize();
    g_nvapi.ok = (status == 0); // NVAPI_OK == 0
    return g_nvapi.ok;
}

static void NvapiUnload()
{
    if (g_nvapi.ok && g_nvapi.Unload) g_nvapi.Unload();
    if (g_nvapi.dll) { FreeLibrary(g_nvapi.dll); g_nvapi.dll = nullptr; }
    g_nvapi.ok = false;
}

// ── GPU state ────────────────────────────────────────────────────────────────

enum class GpuMode { Unknown, IGPU, DGPU };
static GpuMode g_currentMode = GpuMode::Unknown;

// Returns true if MUX is currently routed to dGPU
static GpuMode QueryMode()
{
    if (!g_nvapi.ok || !g_nvapi.GetMode) return GpuMode::Unknown;
    unsigned int mode = 0;
    int r = g_nvapi.GetMode(&mode);
    if (r != 0) return GpuMode::Unknown;
    // mode == 1  → dGPU active on display output
    // mode == 0  → iGPU active (Optimus/auto)
    return (mode == 1) ? GpuMode::DGPU : GpuMode::IGPU;
}

static bool SetMode(GpuMode target)
{
    if (!g_nvapi.ok || !g_nvapi.SetDGPU) return false;
    unsigned int enable = (target == GpuMode::DGPU) ? 1u : 0u;
    int r = g_nvapi.SetDGPU(0, enable); // gpuIndex 0 = primary dGPU
    return (r == 0);
}

// ── Tray icon rendering ──────────────────────────────────────────────────────
// We paint a 16×16 DIB with a filled circle and a centred letter.
// No external resources; fully self-contained.

static HICON MakeLetterIcon(WCHAR letter, COLORREF bg, COLORREF fg)
{
    const int SZ = 16;

    // ── 1. Create a compatible DC and a 32-bpp DIB ───────────────────────────
    HDC hdcScreen = GetDC(nullptr);
    HDC hdcMem    = CreateCompatibleDC(hdcScreen);

    BITMAPINFOHEADER bih = {};
    bih.biSize        = sizeof(bih);
    bih.biWidth       = SZ;
    bih.biHeight      = -SZ; // top-down
    bih.biPlanes      = 1;
    bih.biBitCount    = 32;
    bih.biCompression = BI_RGB;

    BITMAPINFO bi = {};
    bi.bmiHeader = bih;

    void* bits = nullptr;
    HBITMAP hBmp = CreateDIBSection(hdcMem, &bi, DIB_RGB_COLORS, &bits, nullptr, 0);
    HBITMAP hOld = (HBITMAP)SelectObject(hdcMem, hBmp);

    // ── 2. Paint filled circle ───────────────────────────────────────────────
    HBRUSH hBrush = CreateSolidBrush(bg);
    HPEN   hPen   = CreatePen(PS_SOLID, 1, bg);
    HPEN   hOldP  = (HPEN)SelectObject(hdcMem, hPen);
    HBRUSH hOldB  = (HBRUSH)SelectObject(hdcMem, hBrush);

    // Transparent fill first
    RECT rc = {0, 0, SZ, SZ};
    FillRect(hdcMem, &rc, (HBRUSH)GetStockObject(BLACK_BRUSH));

    Ellipse(hdcMem, 0, 0, SZ, SZ);

    SelectObject(hdcMem, hOldP);
    SelectObject(hdcMem, hOldB);
    DeleteObject(hBrush);
    DeleteObject(hPen);

    // ── 3. Draw the letter centred ───────────────────────────────────────────
    HFONT hFont = CreateFontW(
        11, 0, 0, 0, FW_BOLD, FALSE, FALSE, FALSE,
        DEFAULT_CHARSET, OUT_DEFAULT_PRECIS, CLIP_DEFAULT_PRECIS,
        CLEARTYPE_QUALITY, VARIABLE_PITCH | FF_SWISS,
        L"Segoe UI"
    );
    HFONT hOldF = (HFONT)SelectObject(hdcMem, hFont);
    SetBkMode(hdcMem, TRANSPARENT);
    SetTextColor(hdcMem, fg);

    WCHAR s[2] = {letter, 0};
    DrawTextW(hdcMem, s, 1, &rc, DT_CENTER | DT_VCENTER | DT_SINGLELINE);

    SelectObject(hdcMem, hOldF);
    DeleteObject(hFont);

    // ── 4. Build the mask (1-bit; black = opaque) ────────────────────────────
    HDC     hdcMask = CreateCompatibleDC(hdcScreen);
    HBITMAP hMask   = CreateBitmap(SZ, SZ, 1, 1, nullptr);
    HBITMAP hOldM   = (HBITMAP)SelectObject(hdcMask, hMask);

    // Set mask: pixels matching pure black in the colour bitmap → transparent
    SetBkColor(hdcMem, RGB(0, 0, 0));
    BitBlt(hdcMask, 0, 0, SZ, SZ, hdcMem, 0, 0, SRCCOPY);

    SelectObject(hdcMask, hOldM);
    SelectObject(hdcMem, hOld);

    // ── 5. Compose ICONINFO ──────────────────────────────────────────────────
    ICONINFO ii  = {};
    ii.fIcon     = TRUE;
    ii.hbmColor  = hBmp;
    ii.hbmMask   = hMask;
    HICON hIcon  = CreateIconIndirect(&ii);

    DeleteObject(hBmp);
    DeleteObject(hMask);
    DeleteDC(hdcMem);
    DeleteDC(hdcMask);
    ReleaseDC(nullptr, hdcScreen);

    return hIcon;
}

static HICON g_hIconIGPU   = nullptr;
static HICON g_hIconDGPU   = nullptr;
static HICON g_hIconUnknown= nullptr;

static void CreateIcons()
{
    g_hIconIGPU    = MakeLetterIcon(L'I', RGB(30, 100, 220),  RGB(255, 255, 255)); // blue
    g_hIconDGPU    = MakeLetterIcon(L'N', RGB(30, 180,  60),  RGB(255, 255, 255)); // green
    g_hIconUnknown = MakeLetterIcon(L'?', RGB(120, 120, 120), RGB(255, 255, 255)); // grey
}

static void DestroyIcons()
{
    if (g_hIconIGPU)    { DestroyIcon(g_hIconIGPU);    g_hIconIGPU    = nullptr; }
    if (g_hIconDGPU)    { DestroyIcon(g_hIconDGPU);    g_hIconDGPU    = nullptr; }
    if (g_hIconUnknown) { DestroyIcon(g_hIconUnknown); g_hIconUnknown = nullptr; }
}

// ── Tray management ──────────────────────────────────────────────────────────

#define WM_TRAY   (WM_USER + 1)
#define TRAY_ID   1

static HWND      g_hwnd  = nullptr;
static HINSTANCE g_hInst = nullptr;

// Tooltip text: e.g. "dGPU active — NVIDIA GeForce RTX 4060"
static std::wstring BuildTooltip(GpuMode mode)
{
    if (mode == GpuMode::DGPU)   return L"dGPU active \u2014 NVIDIA (Advanced Optimus)";
    if (mode == GpuMode::IGPU)   return L"iGPU active \u2014 Intel integrated";
    return L"GPU mode unknown";
}

static void UpdateTrayIcon(GpuMode mode)
{
    HICON icon = (mode == GpuMode::DGPU)  ? g_hIconDGPU :
                 (mode == GpuMode::IGPU)  ? g_hIconIGPU :
                                            g_hIconUnknown;
    std::wstring tip = BuildTooltip(mode);

    NOTIFYICONDATA nid  = {};
    nid.cbSize          = sizeof(nid);
    nid.hWnd            = g_hwnd;
    nid.uID             = TRAY_ID;
    nid.uFlags          = NIF_ICON | NIF_TIP;
    nid.hIcon           = icon;
    StringCchCopyW(nid.szTip, ARRAYSIZE(nid.szTip), tip.c_str());
    Shell_NotifyIconW(NIM_MODIFY, &nid);
}

static void AddTrayIcon(GpuMode mode)
{
    HICON icon = (mode == GpuMode::DGPU)  ? g_hIconDGPU :
                 (mode == GpuMode::IGPU)  ? g_hIconIGPU :
                                            g_hIconUnknown;
    std::wstring tip = BuildTooltip(mode);

    NOTIFYICONDATA nid  = {};
    nid.cbSize          = sizeof(nid);
    nid.hWnd            = g_hwnd;
    nid.uID             = TRAY_ID;
    nid.uFlags          = NIF_ICON | NIF_MESSAGE | NIF_TIP;
    nid.uCallbackMessage= WM_TRAY;
    nid.hIcon           = icon;
    StringCchCopyW(nid.szTip, ARRAYSIZE(nid.szTip), tip.c_str());
    Shell_NotifyIconW(NIM_ADD, &nid);
}

static void RemoveTrayIcon()
{
    NOTIFYICONDATA nid = {};
    nid.cbSize = sizeof(nid);
    nid.hWnd   = g_hwnd;
    nid.uID    = TRAY_ID;
    Shell_NotifyIconW(NIM_DELETE, &nid);
}

// ── Window procedure ─────────────────────────────────────────────────────────

#define CMD_REVERT  1
#define CMD_EXIT    2

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    if (msg == WM_TRAY && lParam == WM_RBUTTONUP)
    {
        GpuMode mode = QueryMode();
        std::wstring modeLabel = (mode == GpuMode::DGPU) ? L"Active: dGPU (NVIDIA)"
                               : (mode == GpuMode::IGPU) ? L"Active: iGPU (Intel)"
                               :                           L"Active: Unknown";

        HMENU menu = CreatePopupMenu();
        // Greyed-out status label at top
        AppendMenuW(menu, MF_STRING | MF_GRAYED, 0, modeLabel.c_str());
        AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
        AppendMenuW(menu, MF_STRING, CMD_REVERT, L"Revert to iGPU now");
        AppendMenuW(menu, MF_STRING, CMD_EXIT,   L"Exit (auto-revert)");

        SetForegroundWindow(hwnd); // required to dismiss menu on click-away
        POINT pt;
        GetCursorPos(&pt);
        int cmd = TrackPopupMenu(menu, TPM_RETURNCMD | TPM_NONOTIFY | TPM_RIGHTBUTTON,
                                 pt.x, pt.y, 0, hwnd, nullptr);
        PostMessage(hwnd, WM_NULL, 0, 0); // flush the SetForegroundWindow
        DestroyMenu(menu);

        if (cmd == CMD_REVERT)
        {
            SetMode(GpuMode::IGPU);
            g_currentMode = QueryMode();
            UpdateTrayIcon(g_currentMode);
        }
        else if (cmd == CMD_EXIT)
        {
            PostQuitMessage(0);
        }
    }
    return DefWindowProcW(hwnd, msg, wParam, lParam);
}

// ── Entry point ──────────────────────────────────────────────────────────────

int WINAPI WinMain(HINSTANCE hInst, HINSTANCE, LPSTR, int)
{
    g_hInst = hInst;

    // ── Single-instance guard ─────────────────────────────────────────────
    HANDLE hMutex = CreateMutexW(nullptr, TRUE, L"GpuTraySwitcher_Mutex");
    if (GetLastError() == ERROR_ALREADY_EXISTS)
    {
        MessageBoxW(nullptr,
            L"GPU Tray Switcher is already running.",
            L"Already Running", MB_OK | MB_ICONINFORMATION);
        return 1;
    }

    // ── Create message-only window ────────────────────────────────────────
    WNDCLASSW wc    = {};
    wc.lpfnWndProc  = WndProc;
    wc.hInstance    = hInst;
    wc.lpszClassName= L"GpuTrayClass";
    RegisterClassW(&wc);

    g_hwnd = CreateWindowExW(0, wc.lpszClassName, L"",
                             0, 0, 0, 0, 0,
                             HWND_MESSAGE,   // message-only — never in taskbar
                             nullptr, hInst, nullptr);

    // ── Load icons ────────────────────────────────────────────────────────
    CreateIcons();

    // ── Init NVAPI and switch to dGPU ─────────────────────────────────────
    bool nvapiOk = NvapiLoad();
    if (!nvapiOk)
    {
        // NVAPI not available: show a grey "?" icon and warn once
        AddTrayIcon(GpuMode::Unknown);
        MessageBoxW(nullptr,
            L"NVAPI could not be loaded.\n\n"
            L"This tool requires an NVIDIA driver (510+) and an Advanced Optimus laptop.\n"
            L"The tray icon will remain but GPU switching is unavailable.",
            L"GPU Tray Switcher — NVAPI unavailable",
            MB_OK | MB_ICONWARNING);
    }
    else
    {
        bool switched = SetMode(GpuMode::DGPU);
        g_currentMode = QueryMode();

        if (!switched || g_currentMode != GpuMode::DGPU)
        {
            // SetDGPU call may have succeeded at driver level; re-query after
            // a short spin to let the driver settle (MUX switch is async).
            Sleep(400);
            g_currentMode = QueryMode();
        }

        AddTrayIcon(g_currentMode);

        if (g_currentMode != GpuMode::DGPU)
        {
            // Non-fatal: the driver may require a display reconnect or the
            // system may not support in-session MUX switching. Inform user.
            MessageBoxW(nullptr,
                L"dGPU mode was requested but the active GPU could not be confirmed.\n\n"
                L"Your system may require a display reconnect or logout to complete the switch.\n"
                L"Some Advanced Optimus implementations only apply the MUX change at next login.",
                L"GPU Tray Switcher \u2014 Note",
                MB_OK | MB_ICONINFORMATION);
        }
    }

    // ── Message loop ──────────────────────────────────────────────────────
    MSG msg;
    while (GetMessage(&msg, nullptr, 0, 0))
    {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    // ── Cleanup: revert to iGPU, remove tray icon ─────────────────────────
    if (nvapiOk)
    {
        SetMode(GpuMode::IGPU);
        // Briefly show iGPU icon as visual confirmation before exit
        UpdateTrayIcon(GpuMode::IGPU);
        Sleep(600);
    }

    RemoveTrayIcon();
    NvapiUnload();
    DestroyIcons();

    ReleaseMutex(hMutex);
    CloseHandle(hMutex);
    return 0;
}
